version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - pip install --upgrade pip
    - pip install -e .[docs]

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false
  
formats:
  - html
