version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: . # Install the main project in editable mode

sphinx:
  configuration: docs/conf.py
  html_dir: _build/html

formats:
  - html
