version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    - pip install --upgrade pip
    - pip install -e .[docs]

sphinx:
  configuration: docs/conf.py
  
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

formats:
  - htmlzip
  - pdf
  - epub
